FROM node:25-bookworm-slim

WORKDIR /app

COPY package*.json ./

# npm ci estricto, pero tolera peer deps conflictivas
RUN npm ci --legacy-peer-deps --no-audit --no-fund

COPY . .

EXPOSE 4200
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--poll", "1000"]
